const express = require('express');
const EFIR = require('../models/EFIR');
const { protect, authorize } = require('../middleware/auth');

const router = express.Router();

const generateEFIRNumber = () => {
  const year = new Date().getFullYear();
  const random = Math.floor(1000 + Math.random() * 9000);
  return `EFIR/${year}/${random}`;
};

// @route   GET /api/efirs
router.get('/', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const { search, status, incidentType } = req.query;
    let query = {};

    if (status) query.status = status;
    if (incidentType) query.incidentType = incidentType;

    let efirs = await EFIR.find(query)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber')
      .populate('verifiedBy', 'name email')
      .sort({ createdAt: -1 });

    if (search) {
      const s = search.toLowerCase();
      efirs = efirs.filter(
        (e) =>
          e.efirNumber.toLowerCase().includes(s) ||
          e.tourist?.user?.name?.toLowerCase().includes(s) ||
          e.incidentType.toLowerCase().includes(s)
      );
    }

    res.json(efirs);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   GET /api/efirs/stats
router.get('/stats', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const total = await EFIR.countDocuments();
    const verified = await EFIR.countDocuments({ status: 'Verified' });
    const pending = await EFIR.countDocuments({ status: 'Pending' });
    const startOfMonth = new Date();
    startOfMonth.setDate(1);
    startOfMonth.setHours(0, 0, 0, 0);
    const thisMonth = await EFIR.countDocuments({ createdAt: { $gte: startOfMonth } });
    res.json({ total, verified, pending, thisMonth });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   GET /api/efirs/:id
router.get('/:id', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.findById(req.params.id)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber department')
      .populate('verifiedBy', 'name email')
      .populate('alert');
    if (!efir) return res.status(404).json({ message: 'E-FIR not found' });
    res.json(efir);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   GET /api/efirs/:id/download
router.get('/:id/download', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.findById(req.params.id)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber');

    if (!efir) return res.status(404).json({ message: 'E-FIR not found' });

    const report = `
ELECTRONIC FIRST INFORMATION REPORT (E-FIR)
============================================
E-FIR Number    : ${efir.efirNumber}
Status          : ${efir.status}
Generated Date  : ${new Date(efir.createdAt).toLocaleString()}

TOURIST INFORMATION
-------------------
Name            : ${efir.tourist?.user?.name || 'N/A'}
Tourist ID      : ${efir.tourist?.touristId || 'N/A'}
Email           : ${efir.tourist?.user?.email || 'N/A'}
Phone           : ${efir.tourist?.user?.phone || 'N/A'}

INCIDENT DETAILS
----------------
Incident Type   : ${efir.incidentType}
Severity        : ${efir.severity}
Location        : ${efir.location?.address || 'N/A'}
Date & Time     : ${new Date(efir.incidentDate).toLocaleString()}
Description     : ${efir.description}

REPORT DETAILS
--------------
Source          : ${efir.source}
Assigned Officer: ${efir.assignedOfficer?.name || 'Unassigned'}
Response Action : ${efir.responseAction}
============================================
Generated by Smart Tourist Safety Monitoring System
    `.trim();

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="${efir.efirNumber.replace(/\//g, '-')}.txt"`);
    res.send(report);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   POST /api/efirs
router.post('/', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.create({
      ...req.body,
      efirNumber: generateEFIRNumber(),
      assignedOfficer: req.body.assignedOfficer || req.user._id,
    });
    const populated = await EFIR.findById(efir._id)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber');
    res.status(201).json(populated);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   PUT /api/efirs/:id/verify
router.put('/:id/verify', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.findById(req.params.id);
    if (!efir) return res.status(404).json({ message: 'E-FIR not found' });

    efir.status = 'Verified';
    efir.verifiedBy = req.user._id;
    efir.verifiedAt = new Date();
    await efir.save();

    const populated = await EFIR.findById(efir._id)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber')
      .populate('verifiedBy', 'name email');

    res.json(populated);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   PUT /api/efirs/:id
router.put('/:id', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.findById(req.params.id);
    if (!efir) return res.status(404).json({ message: 'E-FIR not found' });

    const fields = ['incidentType', 'severity', 'description', 'status', 'source', 'responseAction', 'assignedOfficer', 'location', 'incidentDate'];
    fields.forEach((field) => {
      if (req.body[field] !== undefined) efir[field] = req.body[field];
    });

    if (req.body.status === 'Verified' && efir.status !== 'Verified') {
      efir.verifiedBy = req.user._id;
      efir.verifiedAt = new Date();
    }

    await efir.save();
    const populated = await EFIR.findById(efir._id)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber')
      .populate('verifiedBy', 'name email');
    res.json(populated);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   PUT /api/efirs/:id/close
router.put('/:id/close', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.findById(req.params.id);
    if (!efir) return res.status(404).json({ message: 'E-FIR not found' });

    efir.status = 'Closed';
    efir.responseAction = req.body.responseAction || 'Case closed by officer';
    await efir.save();

    const populated = await EFIR.findById(efir._id)
      .populate({ path: 'tourist', populate: { path: 'user', select: 'name email phone' } })
      .populate('assignedOfficer', 'name email badgeNumber');
    res.json(populated);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// @route   DELETE /api/efirs/:id
router.delete('/:id', protect, authorize('authority', 'admin'), async (req, res) => {
  try {
    const efir = await EFIR.findById(req.params.id);
    if (!efir) return res.status(404).json({ message: 'E-FIR not found' });
    if (efir.status === 'Verified') {
      return res.status(400).json({ message: 'Cannot delete verified E-FIR records' });
    }
    await efir.deleteOne();
    res.json({ message: 'E-FIR deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
